#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CircleButtonQs.Resource", IsApplication=true)]

namespace CircleButtonQs
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int cb_color = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int cb_pressedRingWidth = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int colorAccent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int colorPrimary = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int colorPrimaryDark = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int ic_launcher_background = 2130837507;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int fab_margin = 2130903040;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int ic_action_tick = 2130968576;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int activity_main = 2131034112;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F060000
			public const int ic_launcher = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int ic_launcher_foreground = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int ic_launcher_round = 2131099650;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int action_settings = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int app_name = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000,0x7F010001 }
			public static int[] CircleButton = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int CircleButton_cb_color = 0;
			
			// aapt resource value: 1
			public const int CircleButton_cb_pressedRingWidth = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
